export const MOCK_HISTORY = [
  {
    id: "1",
    title: "lofi hip hop radio 📚 beats to relax study to",
    format: "mp3",
    sizeLabel: "8.7 MB",
    durationLabel: "03:45:21",
    thumbnail: "https://picsum.photos/seed/lofi/200/200",
  },
  {
    id: "2",
    title: "Switzerland 4K - Beautiful nature with relaxing music",
    format: "mp4",
    sizeLabel: "124.6 MB",
    durationLabel: "12:32",
    thumbnail: "https://picsum.photos/seed/switzerland/200/200",
  },
  {
    id: "3",
    title: "Eminem - Mockingbird (Official Music Video)",
    format: "mp3",
    sizeLabel: "5.6 MB",
    durationLabel: "04:11",
    thumbnail: "https://picsum.photos/seed/eminem/200/200",
  },
  {
    id: "4",
    title: "Summer Vibes Mix 2024 ☀️ Best Of Tropical Deep House",
    format: "mp3",
    sizeLabel: "9.2 MB",
    durationLabel: "01:05:15",
    thumbnail: "https://picsum.photos/seed/summer/200/200",
  },
  {
    id: "5",
    title: "The power of habits | Charles Duhigg | TEDx",
    format: "mp4",
    sizeLabel: "96.3 MB",
    durationLabel: "18:40",
    thumbnail: "https://picsum.photos/seed/tedx/200/200",
  },
  {
    id: "6",
    title: "Funny Dogs and Cats Videos 2024 🐱 Best Animals",
    format: "mp4",
    sizeLabel: "67.8 MB",
    durationLabel: "10:05",
    thumbnail: "https://picsum.photos/seed/animals/200/200",
  },
];