export const MOCK_HISTORY = [
  {
    id: "1",
    title: "lofi hip hop radio 📚 beats to relax study to",
    format: "mp3",
    sizeLabel: "8.7 MB",
    sizeMB: 8.7,
    durationLabel: "03:45:21",
    durationSeconds: 13521,
    thumbnail: "https://picsum.photos/seed/lofi/200/200",
    url: "https://youtube.com/watch?v=jfKfPfyJRdk",
  },
  {
    id: "2",
    title: "Switzerland 4K - Beautiful nature with relaxing music",
    format: "mp4",
    sizeLabel: "124.6 MB",
    sizeMB: 124.6,
    durationLabel: "12:32",
    durationSeconds: 752,
    thumbnail: "https://picsum.photos/seed/switzerland/200/200",
    url: "https://youtube.com/watch?v=sample2",
  },
  {
    id: "3",
    title: "Eminem - Mockingbird (Official Music Video)",
    format: "mp3",
    sizeLabel: "5.6 MB",
    sizeMB: 5.6,
    durationLabel: "04:11",
    durationSeconds: 251,
    thumbnail: "https://picsum.photos/seed/eminem/200/200",
    url: "https://youtube.com/watch?v=S9bCLPwzSC0",
  },
  {
    id: "4",
    title: "Summer Vibes Mix 2024 ☀️ Best Of Tropical Deep House",
    format: "mp3",
    sizeLabel: "9.2 MB",
    sizeMB: 9.2,
    durationLabel: "01:05:15",
    durationSeconds: 3915,
    thumbnail: "https://picsum.photos/seed/summer/200/200",
    url: "https://youtube.com/watch?v=sample4",
  },
  {
    id: "5",
    title: "The power of habits | Charles Duhigg | TEDx",
    format: "mp4",
    sizeLabel: "96.3 MB",
    sizeMB: 96.3,
    durationLabel: "18:40",
    durationSeconds: 1120,
    thumbnail: "https://picsum.photos/seed/tedx/200/200",
    url: "https://youtube.com/watch?v=sample5",
  },
  {
    id: "6",
    title: "Funny Dogs and Cats Videos 2024 🐱 Best Animals",
    format: "mp4",
    sizeLabel: "67.8 MB",
    sizeMB: 67.8,
    durationLabel: "10:05",
    durationSeconds: 605,
    thumbnail: "https://picsum.photos/seed/animals/200/200",
    url: "https://youtube.com/watch?v=sample6",
  },
];